export const exampleAst = {
  type: "Program",
  start: 0,
  end: 2881,
  body: [
    {
      type: "FunctionDeclaration",
      start: 0,
      end: 2881,
      id: { type: "Identifier", start: 9, end: 12, name: "App" },
      expression: false,
      generator: false,
      async: false,
      params: [],
      body: {
        type: "BlockStatement",
        start: 14,
        end: 2881,
        body: [
          {
            type: "VariableDeclaration",
            start: 15,
            end: 100,
            declarations: [
              {
                type: "VariableDeclarator",
                start: 21,
                end: 99,
                id: {
                  type: "ArrayPattern",
                  start: 21,
                  end: 44,
                  elements: [
                    { type: "Identifier", start: 22, end: 30, name: "formData" },
                    { type: "Identifier", start: 32, end: 43, name: "setFormData" },
                  ],
                },
                init: {
                  type: "CallExpression",
                  start: 47,
                  end: 99,
                  callee: {
                    type: "MemberExpression",
                    start: 47,
                    end: 61,
                    object: { type: "Identifier", start: 47, end: 52, name: "React" },
                    property: { type: "Identifier", start: 53, end: 61, name: "useState" },
                    computed: false,
                    optional: false,
                  },
                  arguments: [
                    {
                      type: "ObjectExpression",
                      start: 62,
                      end: 98,
                      properties: [
                        {
                          type: "Property",
                          start: 64,
                          end: 72,
                          method: false,
                          shorthand: false,
                          computed: false,
                          key: { type: "Identifier", start: 64, end: 68, name: "name" },
                          value: { type: "Literal", start: 70, end: 72, value: "", raw: "" },
                          kind: "init",
                        },
                        {
                          type: "Property",
                          start: 74,
                          end: 83,
                          method: false,
                          shorthand: false,
                          computed: false,
                          key: { type: "Identifier", start: 74, end: 79, name: "email" },
                          value: { type: "Literal", start: 81, end: 83, value: "", raw: "" },
                          kind: "init",
                        },
                        {
                          type: "Property",
                          start: 85,
                          end: 96,
                          method: false,
                          shorthand: false,
                          computed: false,
                          key: { type: "Identifier", start: 85, end: 92, name: "message" },
                          value: { type: "Literal", start: 94, end: 96, value: "", raw: "" },
                          kind: "init",
                        },
                      ],
                    },
                  ],
                  optional: false,
                },
              },
            ],
            kind: "const",
          },
          {
            type: "VariableDeclaration",
            start: 103,
            end: 132,
            declarations: [
              {
                type: "VariableDeclarator",
                start: 109,
                end: 131,
                id: {
                  type: "ObjectPattern",
                  start: 109,
                  end: 118,
                  properties: [
                    {
                      type: "Property",
                      start: 111,
                      end: 116,
                      method: false,
                      shorthand: true,
                      computed: false,
                      key: { type: "Identifier", start: 111, end: 116, name: "toast" },
                      kind: "init",
                      value: { type: "Identifier", start: 111, end: 116, name: "toast" },
                    },
                  ],
                },
                init: {
                  type: "CallExpression",
                  start: 121,
                  end: 131,
                  callee: { type: "Identifier", start: 121, end: 129, name: "useToast" },
                  arguments: [],
                  optional: false,
                },
              },
            ],
            kind: "const",
          },
          {
            type: "VariableDeclaration",
            start: 136,
            end: 254,
            declarations: [
              {
                type: "VariableDeclarator",
                start: 142,
                end: 253,
                id: { type: "Identifier", start: 142, end: 159, name: "handleInputChange" },
                init: {
                  type: "ArrowFunctionExpression",
                  start: 162,
                  end: 253,
                  id: null,
                  expression: false,
                  generator: false,
                  async: false,
                  params: [{ type: "Identifier", start: 163, end: 168, name: "event" }],
                  body: {
                    type: "BlockStatement",
                    start: 173,
                    end: 253,
                    body: [
                      {
                        type: "ExpressionStatement",
                        start: 179,
                        end: 249,
                        expression: {
                          type: "CallExpression",
                          start: 179,
                          end: 248,
                          callee: { type: "Identifier", start: 179, end: 190, name: "setFormData" },
                          arguments: [
                            {
                              type: "ObjectExpression",
                              start: 191,
                              end: 247,
                              properties: [
                                {
                                  type: "SpreadElement",
                                  start: 193,
                                  end: 204,
                                  argument: {
                                    type: "Identifier",
                                    start: 196,
                                    end: 204,
                                    name: "formData",
                                  },
                                },
                                {
                                  type: "Property",
                                  start: 206,
                                  end: 245,
                                  method: false,
                                  shorthand: false,
                                  computed: true,
                                  key: {
                                    type: "MemberExpression",
                                    start: 207,
                                    end: 224,
                                    object: {
                                      type: "MemberExpression",
                                      start: 207,
                                      end: 219,
                                      object: {
                                        type: "Identifier",
                                        start: 207,
                                        end: 212,
                                        name: "event",
                                      },
                                      property: {
                                        type: "Identifier",
                                        start: 213,
                                        end: 219,
                                        name: "target",
                                      },
                                      computed: false,
                                      optional: false,
                                    },
                                    property: {
                                      type: "Identifier",
                                      start: 220,
                                      end: 224,
                                      name: "name",
                                    },
                                    computed: false,
                                    optional: false,
                                  },
                                  value: {
                                    type: "MemberExpression",
                                    start: 227,
                                    end: 245,
                                    object: {
                                      type: "MemberExpression",
                                      start: 227,
                                      end: 239,
                                      object: {
                                        type: "Identifier",
                                        start: 227,
                                        end: 232,
                                        name: "event",
                                      },
                                      property: {
                                        type: "Identifier",
                                        start: 233,
                                        end: 239,
                                        name: "target",
                                      },
                                      computed: false,
                                      optional: false,
                                    },
                                    property: {
                                      type: "Identifier",
                                      start: 240,
                                      end: 245,
                                      name: "value",
                                    },
                                    computed: false,
                                    optional: false,
                                  },
                                  kind: "init",
                                },
                              ],
                            },
                          ],
                          optional: false,
                        },
                      },
                    ],
                  },
                },
              },
            ],
            kind: "const",
          },
          {
            type: "VariableDeclaration",
            start: 258,
            end: 989,
            declarations: [
              {
                type: "VariableDeclarator",
                start: 264,
                end: 988,
                id: { type: "Identifier", start: 264, end: 276, name: "handleSubmit" },
                init: {
                  type: "ArrowFunctionExpression",
                  start: 279,
                  end: 988,
                  id: null,
                  expression: false,
                  generator: false,
                  async: true,
                  params: [{ type: "Identifier", start: 286, end: 291, name: "event" }],
                  body: {
                    type: "BlockStatement",
                    start: 296,
                    end: 988,
                    body: [
                      {
                        type: "ExpressionStatement",
                        start: 302,
                        end: 325,
                        expression: {
                          type: "CallExpression",
                          start: 302,
                          end: 324,
                          callee: {
                            type: "MemberExpression",
                            start: 302,
                            end: 322,
                            object: { type: "Identifier", start: 302, end: 307, name: "event" },
                            property: {
                              type: "Identifier",
                              start: 308,
                              end: 322,
                              name: "preventDefault",
                            },
                            computed: false,
                            optional: false,
                          },
                          arguments: [],
                          optional: false,
                        },
                      },
                      {
                        type: "TryStatement",
                        start: 330,
                        end: 984,
                        block: {
                          type: "BlockStatement",
                          start: 334,
                          end: 866,
                          body: [
                            {
                              type: "VariableDeclaration",
                              start: 342,
                              end: 548,
                              declarations: [
                                {
                                  type: "VariableDeclarator",
                                  start: 348,
                                  end: 547,
                                  id: {
                                    type: "Identifier",
                                    start: 348,
                                    end: 356,
                                    name: "response",
                                  },
                                  init: {
                                    type: "AwaitExpression",
                                    start: 359,
                                    end: 547,
                                    argument: {
                                      type: "CallExpression",
                                      start: 365,
                                      end: 547,
                                      callee: {
                                        type: "Identifier",
                                        start: 365,
                                        end: 370,
                                        name: "fetch",
                                      },
                                      arguments: [
                                        {
                                          type: "Literal",
                                          start: 371,
                                          end: 395,
                                          value: "/api/data/contact-form",
                                          raw: "/api/data/contact-form",
                                        },
                                        {
                                          type: "ObjectExpression",
                                          start: 397,
                                          end: 546,
                                          properties: [
                                            {
                                              type: "Property",
                                              start: 407,
                                              end: 421,
                                              method: false,
                                              shorthand: false,
                                              computed: false,
                                              key: {
                                                type: "Identifier",
                                                start: 407,
                                                end: 413,
                                                name: "method",
                                              },
                                              value: {
                                                type: "Literal",
                                                start: 415,
                                                end: 421,
                                                value: "POST",
                                                raw: "POST",
                                              },
                                              kind: "init",
                                            },
                                            {
                                              type: "Property",
                                              start: 431,
                                              end: 497,
                                              method: false,
                                              shorthand: false,
                                              computed: false,
                                              key: {
                                                type: "Identifier",
                                                start: 431,
                                                end: 438,
                                                name: "headers",
                                              },
                                              value: {
                                                type: "ObjectExpression",
                                                start: 440,
                                                end: 497,
                                                properties: [
                                                  {
                                                    type: "Property",
                                                    start: 452,
                                                    end: 486,
                                                    method: false,
                                                    shorthand: false,
                                                    computed: false,
                                                    key: {
                                                      type: "Literal",
                                                      start: 452,
                                                      end: 466,
                                                      value: "Content-Type",
                                                      raw: "Content-Type",
                                                    },
                                                    value: {
                                                      type: "Literal",
                                                      start: 468,
                                                      end: 486,
                                                      value: "application/json",
                                                      raw: "application/json",
                                                    },
                                                    kind: "init",
                                                  },
                                                ],
                                              },
                                              kind: "init",
                                            },
                                            {
                                              type: "Property",
                                              start: 507,
                                              end: 537,
                                              method: false,
                                              shorthand: false,
                                              computed: false,
                                              key: {
                                                type: "Identifier",
                                                start: 507,
                                                end: 511,
                                                name: "body",
                                              },
                                              value: {
                                                type: "CallExpression",
                                                start: 513,
                                                end: 537,
                                                callee: {
                                                  type: "MemberExpression",
                                                  start: 513,
                                                  end: 527,
                                                  object: {
                                                    type: "Identifier",
                                                    start: 513,
                                                    end: 517,
                                                    name: "JSON",
                                                  },
                                                  property: {
                                                    type: "Identifier",
                                                    start: 518,
                                                    end: 527,
                                                    name: "stringify",
                                                  },
                                                  computed: false,
                                                  optional: false,
                                                },
                                                arguments: [
                                                  {
                                                    type: "Identifier",
                                                    start: 528,
                                                    end: 536,
                                                    name: "formData",
                                                  },
                                                ],
                                                optional: false,
                                              },
                                              kind: "init",
                                            },
                                          ],
                                        },
                                      ],
                                      optional: false,
                                    },
                                  },
                                },
                              ],
                              kind: "const",
                            },
                            {
                              type: "IfStatement",
                              start: 556,
                              end: 670,
                              test: {
                                type: "UnaryExpression",
                                start: 560,
                                end: 572,
                                operator: "!",
                                prefix: true,
                                argument: {
                                  type: "MemberExpression",
                                  start: 561,
                                  end: 572,
                                  object: {
                                    type: "Identifier",
                                    start: 561,
                                    end: 569,
                                    name: "response",
                                  },
                                  property: {
                                    type: "Identifier",
                                    start: 570,
                                    end: 572,
                                    name: "ok",
                                  },
                                  computed: false,
                                  optional: false,
                                },
                              },
                              consequent: {
                                type: "BlockStatement",
                                start: 574,
                                end: 670,
                                body: [
                                  {
                                    type: "ThrowStatement",
                                    start: 584,
                                    end: 662,
                                    argument: {
                                      type: "NewExpression",
                                      start: 590,
                                      end: 661,
                                      callee: {
                                        type: "Identifier",
                                        start: 594,
                                        end: 599,
                                        name: "Error",
                                      },
                                      arguments: [
                                        {
                                          type: "Literal",
                                          start: 600,
                                          end: 660,
                                          value:
                                            "There was an issue with your submission. Please try again.",
                                          raw: "There was an issue with your submission. Please try again.",
                                        },
                                      ],
                                    },
                                  },
                                ],
                              },
                              alternate: null,
                            },
                            {
                              type: "ExpressionStatement",
                              start: 678,
                              end: 802,
                              expression: {
                                type: "CallExpression",
                                start: 678,
                                end: 801,
                                callee: { type: "Identifier", start: 678, end: 683, name: "toast" },
                                arguments: [
                                  {
                                    type: "ObjectExpression",
                                    start: 684,
                                    end: 800,
                                    properties: [
                                      {
                                        type: "Property",
                                        start: 694,
                                        end: 711,
                                        method: false,
                                        shorthand: false,
                                        computed: false,
                                        key: {
                                          type: "Identifier",
                                          start: 694,
                                          end: 699,
                                          name: "title",
                                        },
                                        value: {
                                          type: "Literal",
                                          start: 701,
                                          end: 711,
                                          value: "Success!",
                                          raw: "Success!",
                                        },
                                        kind: "init",
                                      },
                                      {
                                        type: "Property",
                                        start: 721,
                                        end: 791,
                                        method: false,
                                        shorthand: false,
                                        computed: false,
                                        key: {
                                          type: "Identifier",
                                          start: 721,
                                          end: 732,
                                          name: "description",
                                        },
                                        value: {
                                          type: "Literal",
                                          start: 734,
                                          end: 791,
                                          value:
                                            "Your message has been sent. We’ll get back to you soon.",
                                          raw: "Your message has been sent. We’ll get back to you soon.",
                                        },
                                        kind: "init",
                                      },
                                    ],
                                  },
                                ],
                                optional: false,
                              },
                            },
                            {
                              type: "ExpressionStatement",
                              start: 810,
                              end: 860,
                              expression: {
                                type: "CallExpression",
                                start: 810,
                                end: 859,
                                callee: {
                                  type: "Identifier",
                                  start: 810,
                                  end: 821,
                                  name: "setFormData",
                                },
                                arguments: [
                                  {
                                    type: "ObjectExpression",
                                    start: 822,
                                    end: 858,
                                    properties: [
                                      {
                                        type: "Property",
                                        start: 824,
                                        end: 832,
                                        method: false,
                                        shorthand: false,
                                        computed: false,
                                        key: {
                                          type: "Identifier",
                                          start: 824,
                                          end: 828,
                                          name: "name",
                                        },
                                        value: {
                                          type: "Literal",
                                          start: 830,
                                          end: 832,
                                          value: "",
                                          raw: "",
                                        },
                                        kind: "init",
                                      },
                                      {
                                        type: "Property",
                                        start: 834,
                                        end: 843,
                                        method: false,
                                        shorthand: false,
                                        computed: false,
                                        key: {
                                          type: "Identifier",
                                          start: 834,
                                          end: 839,
                                          name: "email",
                                        },
                                        value: {
                                          type: "Literal",
                                          start: 841,
                                          end: 843,
                                          value: "",
                                          raw: "",
                                        },
                                        kind: "init",
                                      },
                                      {
                                        type: "Property",
                                        start: 845,
                                        end: 856,
                                        method: false,
                                        shorthand: false,
                                        computed: false,
                                        key: {
                                          type: "Identifier",
                                          start: 845,
                                          end: 852,
                                          name: "message",
                                        },
                                        value: {
                                          type: "Literal",
                                          start: 854,
                                          end: 856,
                                          value: "",
                                          raw: "",
                                        },
                                        kind: "init",
                                      },
                                    ],
                                  },
                                ],
                                optional: false,
                              },
                            },
                          ],
                        },
                        handler: {
                          type: "CatchClause",
                          start: 867,
                          end: 984,
                          param: { type: "Identifier", start: 874, end: 879, name: "error" },
                          body: {
                            type: "BlockStatement",
                            start: 881,
                            end: 984,
                            body: [
                              {
                                type: "ExpressionStatement",
                                start: 889,
                                end: 978,
                                expression: {
                                  type: "CallExpression",
                                  start: 889,
                                  end: 977,
                                  callee: {
                                    type: "Identifier",
                                    start: 889,
                                    end: 894,
                                    name: "toast",
                                  },
                                  arguments: [
                                    {
                                      type: "ObjectExpression",
                                      start: 895,
                                      end: 976,
                                      properties: [
                                        {
                                          type: "Property",
                                          start: 905,
                                          end: 931,
                                          method: false,
                                          shorthand: false,
                                          computed: false,
                                          key: {
                                            type: "Identifier",
                                            start: 905,
                                            end: 910,
                                            name: "title",
                                          },
                                          value: {
                                            type: "Literal",
                                            start: 912,
                                            end: 931,
                                            value: "Submission Failed",
                                            raw: "Submission Failed",
                                          },
                                          kind: "init",
                                        },
                                        {
                                          type: "Property",
                                          start: 941,
                                          end: 967,
                                          method: false,
                                          shorthand: false,
                                          computed: false,
                                          key: {
                                            type: "Identifier",
                                            start: 941,
                                            end: 952,
                                            name: "description",
                                          },
                                          value: {
                                            type: "MemberExpression",
                                            start: 954,
                                            end: 967,
                                            object: {
                                              type: "Identifier",
                                              start: 954,
                                              end: 959,
                                              name: "error",
                                            },
                                            property: {
                                              type: "Identifier",
                                              start: 960,
                                              end: 967,
                                              name: "message",
                                            },
                                            computed: false,
                                            optional: false,
                                          },
                                          kind: "init",
                                        },
                                      ],
                                    },
                                  ],
                                  optional: false,
                                },
                              },
                            ],
                          },
                        },
                        finalizer: null,
                      },
                    ],
                  },
                },
              },
            ],
            kind: "const",
          },
          {
            type: "ReturnStatement",
            start: 993,
            end: 2879,
            argument: {
              type: "JSXElement",
              start: 1006,
              end: 2874,
              openingElement: {
                type: "JSXOpeningElement",
                start: 1006,
                end: 1062,
                attributes: [
                  {
                    type: "JSXAttribute",
                    start: 1011,
                    end: 1061,
                    name: { type: "JSXIdentifier", start: 1011, end: 1020, name: "className" },
                    value: {
                      type: "Literal",
                      start: 1021,
                      end: 1061,
                      value: "bg-teal-200 min-h-screen flex flex-col",
                      raw: "bg-teal-200 min-h-screen flex flex-col",
                    },
                  },
                ],
                name: { type: "JSXIdentifier", start: 1007, end: 1010, name: "div" },
                selfClosing: false,
              },
              closingElement: {
                type: "JSXClosingElement",
                start: 2868,
                end: 2874,
                name: { type: "JSXIdentifier", start: 2870, end: 2873, name: "div" },
              },
              children: [
                { type: "JSXText", start: 1062, end: 1069, value: "\\n      ", raw: "\\n      " },
                {
                  type: "JSXElement",
                  start: 1069,
                  end: 1293,
                  openingElement: {
                    type: "JSXOpeningElement",
                    start: 1069,
                    end: 1112,
                    attributes: [
                      {
                        type: "JSXAttribute",
                        start: 1077,
                        end: 1111,
                        name: { type: "JSXIdentifier", start: 1077, end: 1086, name: "className" },
                        value: {
                          type: "Literal",
                          start: 1087,
                          end: 1111,
                          value: "py-10 px-5 text-center",
                          raw: "py-10 px-5 text-center",
                        },
                      },
                    ],
                    name: { type: "JSXIdentifier", start: 1070, end: 1076, name: "header" },
                    selfClosing: false,
                  },
                  closingElement: {
                    type: "JSXClosingElement",
                    start: 1284,
                    end: 1293,
                    name: { type: "JSXIdentifier", start: 1286, end: 1292, name: "header" },
                  },
                  children: [
                    {
                      type: "JSXText",
                      start: 1112,
                      end: 1121,
                      value: "\\n        ",
                      raw: "\\n        ",
                    },
                    {
                      type: "JSXElement",
                      start: 1121,
                      end: 1183,
                      openingElement: {
                        type: "JSXOpeningElement",
                        start: 1121,
                        end: 1156,
                        attributes: [
                          {
                            type: "JSXAttribute",
                            start: 1125,
                            end: 1155,
                            name: {
                              type: "JSXIdentifier",
                              start: 1125,
                              end: 1134,
                              name: "className",
                            },
                            value: {
                              type: "Literal",
                              start: 1135,
                              end: 1155,
                              value: "text-4xl font-bold",
                              raw: "text-4xl font-bold",
                            },
                          },
                        ],
                        name: { type: "JSXIdentifier", start: 1122, end: 1124, name: "h1" },
                        selfClosing: false,
                      },
                      closingElement: {
                        type: "JSXClosingElement",
                        start: 1178,
                        end: 1183,
                        name: { type: "JSXIdentifier", start: 1180, end: 1182, name: "h1" },
                      },
                      children: [
                        {
                          type: "JSXText",
                          start: 1156,
                          end: 1178,
                          value: "Welcome to Our Agency!",
                          raw: "Welcome to Our Agency!",
                        },
                      ],
                    },
                    {
                      type: "JSXText",
                      start: 1183,
                      end: 1192,
                      value: "\\n        ",
                      raw: "\\n        ",
                    },
                    {
                      type: "JSXElement",
                      start: 1192,
                      end: 1277,
                      openingElement: {
                        type: "JSXOpeningElement",
                        start: 1192,
                        end: 1220,
                        attributes: [
                          {
                            type: "JSXAttribute",
                            start: 1195,
                            end: 1219,
                            name: {
                              type: "JSXIdentifier",
                              start: 1195,
                              end: 1204,
                              name: "className",
                            },
                            value: {
                              type: "Literal",
                              start: 1205,
                              end: 1219,
                              value: "mt-2 text-lg",
                              raw: "mt-2 text-lg",
                            },
                          },
                        ],
                        name: { type: "JSXIdentifier", start: 1193, end: 1194, name: "p" },
                        selfClosing: false,
                      },
                      closingElement: {
                        type: "JSXClosingElement",
                        start: 1273,
                        end: 1277,
                        name: { type: "JSXIdentifier", start: 1275, end: 1276, name: "p" },
                      },
                      children: [
                        {
                          type: "JSXText",
                          start: 1220,
                          end: 1273,
                          value: "We provide top-notch services tailored to your needs.",
                          raw: "We provide top-notch services tailored to your needs.",
                        },
                      ],
                    },
                    {
                      type: "JSXText",
                      start: 1277,
                      end: 1284,
                      value: "\\n      ",
                      raw: "\\n      ",
                    },
                  ],
                },
                {
                  type: "JSXText",
                  start: 1293,
                  end: 1301,
                  value: "\\n\\n      ",
                  raw: "\\n\\n      ",
                },
                {
                  type: "JSXElement",
                  start: 1301,
                  end: 2741,
                  openingElement: {
                    type: "JSXOpeningElement",
                    start: 1301,
                    end: 1340,
                    attributes: [
                      {
                        type: "JSXAttribute",
                        start: 1307,
                        end: 1339,
                        name: { type: "JSXIdentifier", start: 1307, end: 1316, name: "className" },
                        value: {
                          type: "Literal",
                          start: 1317,
                          end: 1339,
                          value: "flex-grow py-10 px-5",
                          raw: "flex-grow py-10 px-5",
                        },
                      },
                    ],
                    name: { type: "JSXIdentifier", start: 1302, end: 1306, name: "main" },
                    selfClosing: false,
                  },
                  closingElement: {
                    type: "JSXClosingElement",
                    start: 2734,
                    end: 2741,
                    name: { type: "JSXIdentifier", start: 2736, end: 2740, name: "main" },
                  },
                  children: [
                    {
                      type: "JSXText",
                      start: 1340,
                      end: 1349,
                      value: "\\n        ",
                      raw: "\\n        ",
                    },
                    {
                      type: "JSXElement",
                      start: 1349,
                      end: 1729,
                      openingElement: {
                        type: "JSXOpeningElement",
                        start: 1349,
                        end: 1376,
                        attributes: [
                          {
                            type: "JSXAttribute",
                            start: 1358,
                            end: 1375,
                            name: {
                              type: "JSXIdentifier",
                              start: 1358,
                              end: 1367,
                              name: "className",
                            },
                            value: {
                              type: "Literal",
                              start: 1368,
                              end: 1375,
                              value: "mb-10",
                              raw: "mb-10",
                            },
                          },
                        ],
                        name: { type: "JSXIdentifier", start: 1350, end: 1357, name: "section" },
                        selfClosing: false,
                      },
                      closingElement: {
                        type: "JSXClosingElement",
                        start: 1719,
                        end: 1729,
                        name: { type: "JSXIdentifier", start: 1721, end: 1728, name: "section" },
                      },
                      children: [
                        {
                          type: "JSXText",
                          start: 1376,
                          end: 1387,
                          value: "\\n          ",
                          raw: "\\n          ",
                        },
                        {
                          type: "JSXElement",
                          start: 1387,
                          end: 1441,
                          openingElement: {
                            type: "JSXOpeningElement",
                            start: 1387,
                            end: 1422,
                            attributes: [
                              {
                                type: "JSXAttribute",
                                start: 1391,
                                end: 1421,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1391,
                                  end: 1400,
                                  name: "className",
                                },
                                value: {
                                  type: "Literal",
                                  start: 1401,
                                  end: 1421,
                                  value: "text-2xl font-bold",
                                  raw: "text-2xl font-bold",
                                },
                              },
                            ],
                            name: { type: "JSXIdentifier", start: 1388, end: 1390, name: "h2" },
                            selfClosing: false,
                          },
                          closingElement: {
                            type: "JSXClosingElement",
                            start: 1436,
                            end: 1441,
                            name: { type: "JSXIdentifier", start: 1438, end: 1440, name: "h2" },
                          },
                          children: [
                            {
                              type: "JSXText",
                              start: 1422,
                              end: 1436,
                              value: "Why Choose Us?",
                              raw: "Why Choose Us?",
                            },
                          ],
                        },
                        {
                          type: "JSXText",
                          start: 1441,
                          end: 1452,
                          value: "\\n          ",
                          raw: "\\n          ",
                        },
                        {
                          type: "JSXElement",
                          start: 1452,
                          end: 1710,
                          openingElement: {
                            type: "JSXOpeningElement",
                            start: 1452,
                            end: 1483,
                            attributes: [
                              {
                                type: "JSXAttribute",
                                start: 1456,
                                end: 1482,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1456,
                                  end: 1465,
                                  name: "className",
                                },
                                value: {
                                  type: "Literal",
                                  start: 1466,
                                  end: 1482,
                                  value: "mt-5 space-y-5",
                                  raw: "mt-5 space-y-5",
                                },
                              },
                            ],
                            name: { type: "JSXIdentifier", start: 1453, end: 1455, name: "ul" },
                            selfClosing: false,
                          },
                          closingElement: {
                            type: "JSXClosingElement",
                            start: 1705,
                            end: 1710,
                            name: { type: "JSXIdentifier", start: 1707, end: 1709, name: "ul" },
                          },
                          children: [
                            {
                              type: "JSXText",
                              start: 1483,
                              end: 1496,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 1496,
                              end: 1555,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 1496,
                                end: 1500,
                                attributes: [],
                                name: { type: "JSXIdentifier", start: 1497, end: 1499, name: "li" },
                                selfClosing: false,
                              },
                              closingElement: {
                                type: "JSXClosingElement",
                                start: 1550,
                                end: 1555,
                                name: { type: "JSXIdentifier", start: 1552, end: 1554, name: "li" },
                              },
                              children: [
                                {
                                  type: "JSXText",
                                  start: 1500,
                                  end: 1550,
                                  value: "We offer personalized solutions for your business.",
                                  raw: "We offer personalized solutions for your business.",
                                },
                              ],
                            },
                            {
                              type: "JSXText",
                              start: 1555,
                              end: 1568,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 1568,
                              end: 1624,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 1568,
                                end: 1572,
                                attributes: [],
                                name: { type: "JSXIdentifier", start: 1569, end: 1571, name: "li" },
                                selfClosing: false,
                              },
                              closingElement: {
                                type: "JSXClosingElement",
                                start: 1619,
                                end: 1624,
                                name: { type: "JSXIdentifier", start: 1621, end: 1623, name: "li" },
                              },
                              children: [
                                {
                                  type: "JSXText",
                                  start: 1572,
                                  end: 1619,
                                  value: "Our team consists of experienced professionals.",
                                  raw: "Our team consists of experienced professionals.",
                                },
                              ],
                            },
                            {
                              type: "JSXText",
                              start: 1624,
                              end: 1637,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 1637,
                              end: 1694,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 1637,
                                end: 1641,
                                attributes: [],
                                name: { type: "JSXIdentifier", start: 1638, end: 1640, name: "li" },
                                selfClosing: false,
                              },
                              closingElement: {
                                type: "JSXClosingElement",
                                start: 1689,
                                end: 1694,
                                name: { type: "JSXIdentifier", start: 1691, end: 1693, name: "li" },
                              },
                              children: [
                                {
                                  type: "JSXText",
                                  start: 1641,
                                  end: 1689,
                                  value: "We value your time and deliver results promptly.",
                                  raw: "We value your time and deliver results promptly.",
                                },
                              ],
                            },
                            {
                              type: "JSXText",
                              start: 1694,
                              end: 1705,
                              value: "\\n          ",
                              raw: "\\n          ",
                            },
                          ],
                        },
                        {
                          type: "JSXText",
                          start: 1710,
                          end: 1719,
                          value: "\\n        ",
                          raw: "\\n        ",
                        },
                      ],
                    },
                    {
                      type: "JSXText",
                      start: 1729,
                      end: 1739,
                      value: "\\n\\n        ",
                      raw: "\\n\\n        ",
                    },
                    {
                      type: "JSXElement",
                      start: 1739,
                      end: 2727,
                      openingElement: {
                        type: "JSXOpeningElement",
                        start: 1739,
                        end: 1748,
                        attributes: [],
                        name: { type: "JSXIdentifier", start: 1740, end: 1747, name: "section" },
                        selfClosing: false,
                      },
                      closingElement: {
                        type: "JSXClosingElement",
                        start: 2717,
                        end: 2727,
                        name: { type: "JSXIdentifier", start: 2719, end: 2726, name: "section" },
                      },
                      children: [
                        {
                          type: "JSXText",
                          start: 1748,
                          end: 1759,
                          value: "\\n          ",
                          raw: "\\n          ",
                        },
                        {
                          type: "JSXElement",
                          start: 1759,
                          end: 1809,
                          openingElement: {
                            type: "JSXOpeningElement",
                            start: 1759,
                            end: 1794,
                            attributes: [
                              {
                                type: "JSXAttribute",
                                start: 1763,
                                end: 1793,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1763,
                                  end: 1772,
                                  name: "className",
                                },
                                value: {
                                  type: "Literal",
                                  start: 1773,
                                  end: 1793,
                                  value: "text-2xl font-bold",
                                  raw: "text-2xl font-bold",
                                },
                              },
                            ],
                            name: { type: "JSXIdentifier", start: 1760, end: 1762, name: "h2" },
                            selfClosing: false,
                          },
                          closingElement: {
                            type: "JSXClosingElement",
                            start: 1804,
                            end: 1809,
                            name: { type: "JSXIdentifier", start: 1806, end: 1808, name: "h2" },
                          },
                          children: [
                            {
                              type: "JSXText",
                              start: 1794,
                              end: 1804,
                              value: "Contact Us",
                              raw: "Contact Us",
                            },
                          ],
                        },
                        {
                          type: "JSXText",
                          start: 1809,
                          end: 1820,
                          value: "\\n          ",
                          raw: "\\n          ",
                        },
                        {
                          type: "JSXElement",
                          start: 1820,
                          end: 2708,
                          openingElement: {
                            type: "JSXOpeningElement",
                            start: 1820,
                            end: 1885,
                            attributes: [
                              {
                                type: "JSXAttribute",
                                start: 1826,
                                end: 1860,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1826,
                                  end: 1835,
                                  name: "className",
                                },
                                value: {
                                  type: "Literal",
                                  start: 1836,
                                  end: 1860,
                                  value: "mt-5 max-w-2xl mx-auto",
                                  raw: "mt-5 max-w-2xl mx-auto",
                                },
                              },
                              {
                                type: "JSXAttribute",
                                start: 1861,
                                end: 1884,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1861,
                                  end: 1869,
                                  name: "onSubmit",
                                },
                                value: {
                                  type: "JSXExpressionContainer",
                                  start: 1870,
                                  end: 1884,
                                  expression: {
                                    type: "Identifier",
                                    start: 1871,
                                    end: 1883,
                                    name: "handleSubmit",
                                  },
                                },
                              },
                            ],
                            name: { type: "JSXIdentifier", start: 1821, end: 1825, name: "form" },
                            selfClosing: false,
                          },
                          closingElement: {
                            type: "JSXClosingElement",
                            start: 2701,
                            end: 2708,
                            name: { type: "JSXIdentifier", start: 2703, end: 2707, name: "form" },
                          },
                          children: [
                            {
                              type: "JSXText",
                              start: 1885,
                              end: 1898,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 1898,
                              end: 2085,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 1898,
                                end: 2085,
                                attributes: [
                                  {
                                    type: "JSXAttribute",
                                    start: 1919,
                                    end: 1930,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 1919,
                                      end: 1923,
                                      name: "name",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 1924,
                                      end: 1930,
                                      value: "name",
                                      raw: "name",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 1945,
                                    end: 1966,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 1945,
                                      end: 1950,
                                      name: "value",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 1951,
                                      end: 1966,
                                      expression: {
                                        type: "MemberExpression",
                                        start: 1952,
                                        end: 1965,
                                        object: {
                                          type: "Identifier",
                                          start: 1952,
                                          end: 1960,
                                          name: "formData",
                                        },
                                        property: {
                                          type: "Identifier",
                                          start: 1961,
                                          end: 1965,
                                          name: "name",
                                        },
                                        computed: false,
                                        optional: false,
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 1981,
                                    end: 2009,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 1981,
                                      end: 1989,
                                      name: "onChange",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 1990,
                                      end: 2009,
                                      expression: {
                                        type: "Identifier",
                                        start: 1991,
                                        end: 2008,
                                        name: "handleInputChange",
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2024,
                                    end: 2047,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2024,
                                      end: 2035,
                                      name: "placeholder",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2036,
                                      end: 2047,
                                      value: "Your Name",
                                      raw: "Your Name",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2062,
                                    end: 2070,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2062,
                                      end: 2070,
                                      name: "required",
                                    },
                                    value: null,
                                  },
                                ],
                                name: {
                                  type: "JSXIdentifier",
                                  start: 1899,
                                  end: 1904,
                                  name: "Input",
                                },
                                selfClosing: true,
                              },
                              closingElement: null,
                              children: [],
                            },
                            {
                              type: "JSXText",
                              start: 2085,
                              end: 2098,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 2098,
                              end: 2315,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 2098,
                                end: 2315,
                                attributes: [
                                  {
                                    type: "JSXAttribute",
                                    start: 2119,
                                    end: 2131,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2119,
                                      end: 2123,
                                      name: "name",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2124,
                                      end: 2131,
                                      value: "email",
                                      raw: "email",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2146,
                                    end: 2158,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2146,
                                      end: 2150,
                                      name: "type",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2151,
                                      end: 2158,
                                      value: "email",
                                      raw: "email",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2173,
                                    end: 2195,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2173,
                                      end: 2178,
                                      name: "value",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 2179,
                                      end: 2195,
                                      expression: {
                                        type: "MemberExpression",
                                        start: 2180,
                                        end: 2194,
                                        object: {
                                          type: "Identifier",
                                          start: 2180,
                                          end: 2188,
                                          name: "formData",
                                        },
                                        property: {
                                          type: "Identifier",
                                          start: 2189,
                                          end: 2194,
                                          name: "email",
                                        },
                                        computed: false,
                                        optional: false,
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2210,
                                    end: 2238,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2210,
                                      end: 2218,
                                      name: "onChange",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 2219,
                                      end: 2238,
                                      expression: {
                                        type: "Identifier",
                                        start: 2220,
                                        end: 2237,
                                        name: "handleInputChange",
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2253,
                                    end: 2277,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2253,
                                      end: 2264,
                                      name: "placeholder",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2265,
                                      end: 2277,
                                      value: "Your Email",
                                      raw: "Your Email",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2292,
                                    end: 2300,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2292,
                                      end: 2300,
                                      name: "required",
                                    },
                                    value: null,
                                  },
                                ],
                                name: {
                                  type: "JSXIdentifier",
                                  start: 2099,
                                  end: 2104,
                                  name: "Input",
                                },
                                selfClosing: true,
                              },
                              closingElement: null,
                              children: [],
                            },
                            {
                              type: "JSXText",
                              start: 2315,
                              end: 2328,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 2328,
                              end: 2552,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 2328,
                                end: 2552,
                                attributes: [
                                  {
                                    type: "JSXAttribute",
                                    start: 2349,
                                    end: 2363,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2349,
                                      end: 2353,
                                      name: "name",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2354,
                                      end: 2363,
                                      value: "message",
                                      raw: "message",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2378,
                                    end: 2391,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2378,
                                      end: 2380,
                                      name: "as",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2381,
                                      end: 2391,
                                      value: "textarea",
                                      raw: "textarea",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2406,
                                    end: 2430,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2406,
                                      end: 2411,
                                      name: "value",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 2412,
                                      end: 2430,
                                      expression: {
                                        type: "MemberExpression",
                                        start: 2413,
                                        end: 2429,
                                        object: {
                                          type: "Identifier",
                                          start: 2413,
                                          end: 2421,
                                          name: "formData",
                                        },
                                        property: {
                                          type: "Identifier",
                                          start: 2422,
                                          end: 2429,
                                          name: "message",
                                        },
                                        computed: false,
                                        optional: false,
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2445,
                                    end: 2473,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2445,
                                      end: 2453,
                                      name: "onChange",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 2454,
                                      end: 2473,
                                      expression: {
                                        type: "Identifier",
                                        start: 2455,
                                        end: 2472,
                                        name: "handleInputChange",
                                      },
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2488,
                                    end: 2514,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2488,
                                      end: 2499,
                                      name: "placeholder",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2500,
                                      end: 2514,
                                      value: "Your Message",
                                      raw: "Your Message",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2529,
                                    end: 2537,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2529,
                                      end: 2537,
                                      name: "required",
                                    },
                                    value: null,
                                  },
                                ],
                                name: {
                                  type: "JSXIdentifier",
                                  start: 2329,
                                  end: 2334,
                                  name: "Input",
                                },
                                selfClosing: true,
                              },
                              closingElement: null,
                              children: [],
                            },
                            {
                              type: "JSXText",
                              start: 2552,
                              end: 2565,
                              value: "\\n            ",
                              raw: "\\n            ",
                            },
                            {
                              type: "JSXElement",
                              start: 2565,
                              end: 2690,
                              openingElement: {
                                type: "JSXOpeningElement",
                                start: 2565,
                                end: 2647,
                                attributes: [
                                  {
                                    type: "JSXAttribute",
                                    start: 2573,
                                    end: 2586,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2573,
                                      end: 2577,
                                      name: "type",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2578,
                                      end: 2586,
                                      value: "submit",
                                      raw: "submit",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2587,
                                    end: 2603,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2587,
                                      end: 2596,
                                      name: "className",
                                    },
                                    value: {
                                      type: "Literal",
                                      start: 2597,
                                      end: 2603,
                                      value: "mt-5",
                                      raw: "mt-5",
                                    },
                                  },
                                  {
                                    type: "JSXAttribute",
                                    start: 2604,
                                    end: 2646,
                                    name: {
                                      type: "JSXIdentifier",
                                      start: 2604,
                                      end: 2611,
                                      name: "onClick",
                                    },
                                    value: {
                                      type: "JSXExpressionContainer",
                                      start: 2612,
                                      end: 2646,
                                      expression: {
                                        type: "ArrowFunctionExpression",
                                        start: 2613,
                                        end: 2645,
                                        id: null,
                                        expression: true,
                                        generator: false,
                                        async: false,
                                        params: [],
                                        body: {
                                          type: "CallExpression",
                                          start: 2619,
                                          end: 2645,
                                          callee: {
                                            type: "MemberExpression",
                                            start: 2619,
                                            end: 2630,
                                            object: {
                                              type: "Identifier",
                                              start: 2619,
                                              end: 2626,
                                              name: "console",
                                            },
                                            property: {
                                              type: "Identifier",
                                              start: 2627,
                                              end: 2630,
                                              name: "log",
                                            },
                                            computed: false,
                                            optional: false,
                                          },
                                          arguments: [
                                            {
                                              type: "Literal",
                                              start: 2631,
                                              end: 2644,
                                              value: "Hello world",
                                              raw: "Hello world",
                                            },
                                          ],
                                          optional: false,
                                        },
                                      },
                                    },
                                  },
                                ],
                                name: {
                                  type: "JSXIdentifier",
                                  start: 2566,
                                  end: 2572,
                                  name: "Button",
                                },
                                selfClosing: false,
                              },
                              closingElement: {
                                type: "JSXClosingElement",
                                start: 2681,
                                end: 2690,
                                name: {
                                  type: "JSXIdentifier",
                                  start: 2683,
                                  end: 2689,
                                  name: "Button",
                                },
                              },
                              children: [
                                {
                                  type: "JSXText",
                                  start: 2647,
                                  end: 2681,
                                  value: "\\n              Submit\\n            ",
                                  raw: "\\n              Submit\\n            ",
                                },
                              ],
                            },
                            {
                              type: "JSXText",
                              start: 2690,
                              end: 2701,
                              value: "\\n          ",
                              raw: "\\n          ",
                            },
                          ],
                        },
                        {
                          type: "JSXText",
                          start: 2708,
                          end: 2717,
                          value: "\\n        ",
                          raw: "\\n        ",
                        },
                      ],
                    },
                    {
                      type: "JSXText",
                      start: 2727,
                      end: 2734,
                      value: "\\n      ",
                      raw: "\\n      ",
                    },
                  ],
                },
                {
                  type: "JSXText",
                  start: 2741,
                  end: 2749,
                  value: "\\n\\n      ",
                  raw: "\\n\\n      ",
                },
                {
                  type: "JSXElement",
                  start: 2749,
                  end: 2863,
                  openingElement: {
                    type: "JSXOpeningElement",
                    start: 2749,
                    end: 2799,
                    attributes: [
                      {
                        type: "JSXAttribute",
                        start: 2757,
                        end: 2798,
                        name: { type: "JSXIdentifier", start: 2757, end: 2766, name: "className" },
                        value: {
                          type: "Literal",
                          start: 2767,
                          end: 2798,
                          value: "py-5 px-5 text-center text-sm",
                          raw: "py-5 px-5 text-center text-sm",
                        },
                      },
                    ],
                    name: { type: "JSXIdentifier", start: 2750, end: 2756, name: "footer" },
                    selfClosing: false,
                  },
                  closingElement: {
                    type: "JSXClosingElement",
                    start: 2854,
                    end: 2863,
                    name: { type: "JSXIdentifier", start: 2856, end: 2862, name: "footer" },
                  },
                  children: [
                    {
                      type: "JSXText",
                      start: 2799,
                      end: 2854,
                      value: "\\n        © 2022 Our Agency. All rights reserved.\\n      ",
                      raw: "\\n        © 2022 Our Agency. All rights reserved.\\n      ",
                    },
                  ],
                },
                { type: "JSXText", start: 2863, end: 2868, value: "\\n    ", raw: "\\n    " },
              ],
            },
          },
        ],
      },
    },
  ],
  sourceType: "script",
}
